cursor_shape block
cursor_opacity 0.7
cursor_beam_thickness 2.5

enable_kitty_keyboard_protocol yes
confirm_os_window_close 0


# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME