general {
    before_sleep_cmd = hyprlock
    after_sleep_cmd  = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Lock screen at 14 minutes
listener {
    timeout = 840
    on-timeout = hyprlock
    on-resume  = hyprctl dispatch dpms on
}

# Suspend at 15 minutes
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
